name: flutter_theme_changer_erfan
description: A Flutter package that allows you to change your app's theme color dynamically with 4 beautiful widgets.
version: 0.0.3+0

repository: https://github.com/erfanalizada/flutter_theme_changer_erfan
homepage: https://github.com/erfanalizada/flutter_theme_changer_erfan
issue_tracker: https://github.com/erfanalizada/flutter_theme_changer_erfan/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - test/goldens/

topics:
  - theme
  - customization
  - ui
  - widgets
